### ISSUE TITLE
"Created By" Background Halftone doesn't size down on mobile sizes

### ISSUE THREAD

**Issue by auttiedot** [fleeting/heartoftexasstickers.com#1]
The halftone texture on the top part of the page is resizing perfectly tho...

![screenshot_20170206-104857](https://cloud.githubusercontent.com/assets/10732907/22658708/a5d4a79e-ec60-11e6-9a99-d628d2755416.png)

**Comment by fleeting** [comment]
@auttiedot This issue was actually because I accidentally left `background: cover` when I changed it to repeat so it was stretching instead of repeating. However, that large halftone image doesn't repeat seamless so I'll need an updated version of it.

**Comment by auttiedot** [comment]
lol I don't know what I was doing when I exported those...
Just updated those to repeat!

**Comment by auttiedot** [comment]
btw I got the pngs fixed so they should repeat up/down and left/right
