### ISSUE TITLE
"Created by" heart looks a little low

### ISSUE THREAD

**Issue by auttiedot** [fleeting/heartoftexasstickers.com#4]
Possible to nudge it up like 1 px? This is another super small thing... If it’s a total pain in the ass, just ignore :P

**Comment by fleeting** [comment]
I can tweak it. Right now it's just the unicode heart so depending on the device it uses the native heart and doesn't look great on iOS (http://apps.timwhitlock.info/emoji/tables/unicode, do a search for heavy black heart). I could do an iOS fallback to http://fontawesome.io/icon/heart/ or if you have a svg of the heart, I can use it instead to keep it seamless.

**Comment by auttiedot** [comment]
Heart svg! I tried something new to make that texture not explode the file size on this, so it's not out of control.
https://www.dropbox.com/sh/9y96vo3w4qmu628/AAAS63EQ5vk7VBzfpQkCDpqba?dl=0

**Comment by fleeting** [comment]
@auttiedot Added the heart. Let me know if the positioning is better.
